// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/takakuwa-s/line-wedding-api/driver"
	"github.com/takakuwa-s/line-wedding-api/dto"
	"github.com/takakuwa-s/line-wedding-api/interface/controller"
	"github.com/takakuwa-s/line-wedding-api/interface/gateway"
	"github.com/takakuwa-s/line-wedding-api/interface/presenter"
	"github.com/takakuwa-s/line-wedding-api/usecase/usecase"
)

// Injectors from wire.go:

func InitializeRouter() *driver.Router {
	weddingLineBot := dto.NewWeddingLineBot()
	messageRepository := gateway.NewMessageRepository()
	adminLineBot := dto.NewAdminLineBot()
	lineGateway := gateway.NewLineGateway(weddingLineBot, adminLineBot)
	faceGateway := gateway.NewFaceGateway()
	firestore := dto.NewFirestore()
	userRepository := gateway.NewUserRepository(firestore)
	fileRepository := gateway.NewFileRepository(firestore)
	binaryRepository := gateway.NewBinaryRepository(firestore)
	linePresenter := presenter.NewLinePresenter(weddingLineBot, adminLineBot)
	commonUtils := usecase.NewCommonUtils(linePresenter, lineGateway)
	adminPushUsecase := usecase.NewAdminPushUsecase(messageRepository, userRepository, commonUtils)
	weddingReplyUsecase := usecase.NewWeddingReplyUsecase(messageRepository, lineGateway, faceGateway, userRepository, fileRepository, binaryRepository, adminPushUsecase, commonUtils)
	weddingLineController := controller.NewWeddingLineController(weddingLineBot, weddingReplyUsecase)
	weddingPushUsecase := usecase.NewWeddingPushUsecase(messageRepository, userRepository, commonUtils)
	adminReplyUsecase := usecase.NewAdminReplyUsecase(messageRepository, lineGateway, weddingPushUsecase, commonUtils)
	adminLineController := controller.NewAdminLineController(adminLineBot, adminReplyUsecase)
	apiUsecase := usecase.NewApiUsecase(userRepository, lineGateway, fileRepository, binaryRepository)
	userApiController := controller.NewUserApiController(apiUsecase)
	fileApiController := controller.NewFileApiController(apiUsecase)
	router := driver.NewRouter(weddingLineController, adminLineController, userApiController, fileApiController)
	return router
}
