// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/takakuwa-s/line-wedding-api/driver"
	"github.com/takakuwa-s/line-wedding-api/dto"
	"github.com/takakuwa-s/line-wedding-api/interface/controller"
	"github.com/takakuwa-s/line-wedding-api/interface/gateway"
	"github.com/takakuwa-s/line-wedding-api/interface/presenter"
	"github.com/takakuwa-s/line-wedding-api/usecase/admin"
	"github.com/takakuwa-s/line-wedding-api/usecase/wedding"
)

// Injectors from wire.go:

func InitializeRouter() *driver.Router {
	weddingLineBot := dto.NewWeddingLineBot()
	adminLineBot := dto.NewAdminLineBot()
	linePresenter := presenter.NewLinePresenter(weddingLineBot, adminLineBot)
	messageRepository := gateway.NewMessageRepository()
	lineRepository := gateway.NewLineRepository(weddingLineBot, adminLineBot)
	userRepository := gateway.NewUserRepository()
	fileRepository := gateway.NewFileRepository()
	weddingReplyUsecase := wedding.NewWeddingReplyUsecase(linePresenter, messageRepository, lineRepository, userRepository, fileRepository)
	weddingLineController := controller.NewWeddingLineController(weddingLineBot, weddingReplyUsecase)
	weddingPushUsecase := wedding.NewWeddingPushUsecase(linePresenter, messageRepository, lineRepository, userRepository)
	adminReplyUsecase := admin.NewAdminReplyUsecase(linePresenter, messageRepository, lineRepository, weddingPushUsecase)
	adminLineController := controller.NewAdminLineController(adminLineBot, adminReplyUsecase)
	router := driver.NewRouter(weddingLineController, adminLineController)
	return router
}
