// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/takakuwa-s/line-wedding-api/driver"
	"github.com/takakuwa-s/line-wedding-api/dto"
	"github.com/takakuwa-s/line-wedding-api/interface/controller"
	"github.com/takakuwa-s/line-wedding-api/interface/gateway"
	"github.com/takakuwa-s/line-wedding-api/usecase/usecase"
)

// Injectors from wire.go:

func InitializeRouter() *driver.FileUploadRouter {
	commonRouter := driver.NewCommonRouter()
	lineBot := dto.NewLineBot()
	lineGateway := gateway.NewLineGateway(lineBot)
	faceGateway := gateway.NewFaceGateway()
	firestore := dto.NewFirestore()
	commonRepository := gateway.NewCommonRepository(firestore)
	fileRepository := gateway.NewFileRepository(commonRepository, firestore)
	binaryRepository := gateway.NewBinaryRepository(firestore)
	fileUploadUsecase := usecase.NewFileUploadUsecase(lineGateway, faceGateway, fileRepository, binaryRepository)
	fileUploadController := controller.NewFileUploadController(fileUploadUsecase)
	fileUploadRouter := driver.NewFileUploadRouter(commonRouter, fileUploadController)
	return fileUploadRouter
}
